[tool.poetry]
name = "phrase hunter"
version = "0.1.0"
description = ""
authors = ["fakeid30 <junayeed@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
